### ISSUE TITLE
Per-group message lists

### ISSUE THREAD

**Issue by ghost** [DominicLuidold/SimpleBroadcast#1]
<i>!! Copied from old ticket system (BukkitDev) !!</i>

Hello. :)

It would be nice to be able to create multiple message lists, and assign them to a permission.
In the config, we would add separated lists and give them a name. Then this name would be used in the permission.

For example, if I have a "player" list, the permission to receive messages from that list could be:
simplebroadcast.messages.player

(of course "messages" could be something else, you choose).

**Comment by KingDome24** [comment]
Hello,

permissions are now supported as you suggested it. :)

Kind regards,
KingDome24
