### ISSUE TITLE
Support ticket

### ISSUE THREAD

**Issue by Nano1778** [DominicLuidold/SimpleBroadcast#10]
This is a support ticket for my issue that I posted about on the bukkit page and was told to post here. I have posted everything I had before and somemore.

Hello I have a problem with most to all the chat plugins on my server including simple broadcast. There is always some sort of problem with the plugin such as with simple broadcast it only uses its default settings. With chatguard it is banning people for (even though i didnt tell it to do that) for saying anything at all! And finally with essentials chat it wont use the chat format I give it it only uses the default chat format. I just installed mods onto the server with cauldron and they stopped working but these plugins as far as I know were working with cauldron but without mods. If you can help it would be most appreciated thanks ;). Also the server is 1.7.10.

Mods on the Server: bibliocraft forbidden magic (thaumcraft addon) mantle (tinkers construct core mod) tinkers construct thaumcraft thaumic tinkerer (thaumcraft addon) backpacks mod magical crops

Chat Plugins: Essentials chat chatguard simple broadcast

server jar file: cauldron 1.7.10

server version: 1.7.10

modpack in use:  http://technicpack.net/modpack/official-runic-pvp-modpack.555192

**Comment by KingDome24** [comment]
Hello,

it would be great if you could upload your config and also your server.log/latest.log on pastebin.com (in two different pastes please) and to share the links here in the ticket.
I'll then have a look into your problem.

Kind regards,
KingDome24

**Comment by GreenFoxx** [comment]
ok here are the links

config: http://pastebin.com/GC63QAb2

fml-server-latest.log: http://pastebin.com/bBZydFU5

latest.log: http://pastebin.com/9EgfmkvL

**Comment by KingDome24** [comment]
Hello,

there are many issues from other plugins in your fml-server-latest.log.
I'd advise you to fix these errors and then to check if SimpleBroadcasts works (again) properly.

KingDome24

**Comment by GreenFoxx** [comment]
if you could please tell me the plugins with issues it would be very appreiciated because id like to use you plugin I like it very much

**Comment by KingDome24** [comment]
Hello,

it looks like I missed the fact that you're using a " ' " (single quote) within one of your messages:
``- '&5Go to &9runicpvp.enjin.com &5for the server's official website!'``
This message should look like this:
``- '&5Go to &9runicpvp.enjin.com &5for the server%sq%s official website!'``
After this change your configuration should work again and SimpleBroadcast will broadcast your messages.

To get some help with the other issues of the plugins I recommend you to visit a board like MinecraftForum.net to get appropriate help.

Kind regards,
KingDome24
