### ISSUE TITLE
Config Resetting

### ISSUE THREAD

**Issue by UntoldFury** [DominicLuidold/SimpleBroadcast#11]
Every time we try and add a broadcast in, it will reset the config. We aren't sure what is causing this, and it is getting really annoying.

**Comment by KingDome24** [comment]
Hello,

it would be great if you could attach your server.log/latest.log as well as your config somewhere (like pastebin) and share the link here. Moreover it would be gerat if you could tell me the text you want to add via the command.

KingDome24
