### ISSUE TITLE
Bossbar doesn't work Glitch?

### ISSUE THREAD

**Issue by austinstiefel** [DominicLuidold/SimpleBroadcast#13]
I have configured the bossbar correctly and enabled it, yet when i go on my server and do /sb bossbar start it doesn't start it but displays a message saying: Boss bar broadcast is disabled (as set in the bossbar.yml)! Same thing when i try to do /sb bossbar stop it says: Boss bar broadcast is allready disabled (as set in the bossbar.yml)! Anyone know whats wrong? Is this a major bug?..

**Comment by KingDome24** [comment]
Hello,

did you reload the plugin after the change in the bossbar.yml?

Kind regards,
KingDome24

**Comment by Veltzkree** [comment]
yes i did. Reloaded config, restarted server, everything...still nothing.

**Comment by KingDome24** [comment]
Hello,

could you maybe create a video and demonstrate how you did it? Unfortunately I'm currently not able to reproduce your problem.

Kind regards,
KingDome24
