### ISSUE TITLE
ActionBarAPI Support

### ISSUE THREAD

**Issue by LukvonStrom** [DominicLuidold/SimpleBroadcast#17]
Could you please add support for http://www.spigotmc.org/resources/actionbarapi.1315/ as a optionally replacement for BarAPI which is very buggy.

**Comment by KingDome24** [comment]
Hello,

I won't replace BarAPI because it became an essential feature of the plugin.
I also think that I won't use this API. Certainly I'll write such a simple class by myself to be able to support the ActionBar.

Kind regards,
KingDome24

**Comment by KingDome24** [comment]
Hello,

I decided to not add this feature because I don't see the sense behind spamming the user with those big sized messages.
I'm sorry.

Kind regards,
KingDome24
