### ISSUE TITLE
Cannot use the ' character in messages.

### ISSUE THREAD

**Issue by weakwizard** [DominicLuidold/SimpleBroadcast#19]
As per the title you cannot use the ' character in the messages.

**Comment by KingDome24** [comment]
Hello,

this is completely intended as single quotes confines the messages. Please use "%sq%" instead to achieve your wished text layout.

Kind regards,
KingDome24

**Comment by weakwizard** [comment]
I also discovered when googling the issue you can use two of them in a row to print it. That is YAML standards.

**Comment by KingDome24** [comment]
Hello,

this is of course also an option but I think this is a potential error source. Due to this the plugin provides the variable "%sq%".

Kind regards,
KingDome24
