### ISSUE TITLE
"Broadcast" Prefix can't be edited. 

### ISSUE THREAD

**Issue by ghost** [DominicLuidold/SimpleBroadcast#20]
Hello,

I tried to edit the prefix to change it to our server initials but it won't change. I can't disable it either. See the screenshots below.

![image](https://cloud.githubusercontent.com/assets/12205893/10081238/86ba5080-6326-11e5-8580-e31052286de1.png)

![image](https://cloud.githubusercontent.com/assets/12205893/10081248/9692686c-6326-11e5-8c83-481de41a9fff.png)

**Comment by KingDome24** [comment]
Hello,

I'll have a look into this problem. It's maybe connected to http://dev.bukkit.org/bukkit-plugins/simplebroadcast/#c152.

Kind regards,
KingDome24

**Comment by tristankhalil** [comment]
Thank you for taking time to check. I really like your plugin! No messy config. :+1:

**Comment by tristankhalil** [comment]
Hello,

I think the issue is resolved. You really need to restart your server at the console for changes to take effect. Using the /simplebroadcast reload won't work on the prefix but will work on the messages (formatting/color/etc)

**Comment by KingDome24** [comment]
Hello,

I wouldn't say it's resolved because normally "/sb reload" should exactly do what you first expected.
I will work on this. :)

Kind regards,
KingDome24
