### ISSUE TITLE
UUID Fetcher causing crashes

### ISSUE THREAD

**Issue by Corcustos** [DominicLuidold/SimpleBroadcast#23]
My server has been experiencing random crashes as of late, and it appears that SimpleBroadcast is causing them. At first I did not know that it was SimpleBroadcast, but I later had someone more experienced than I am at these things tell me that the plugin "simplebroadcast" is trying to use UUID fetcher, which is causing the crash. I am currentlly using the latest version of the plugin, and I believe the latest version of Spigot. However, I may be a bit behind on Spigot. Not sure.

Here is a pastebin of the console output: http://pastebin.com/anSNHzpH

Also, I thought I might bring this up. Players are using the "Hehehe... Thank you for using SimpleBroadcast!" message to spam while muted. If players attempt to say "SimpleBroadcast" while muted, the message still players. I was hoping that you could fix this as well.

I appreciate any help/information that can be provided to fix these issues. Thanks

~Corcustos

**Comment by KingDome24** [comment]
Hello,

thanks for your report. Your initially mentioned issue seems to be connected to #22 
I will have a look into this to prevent servers from crashing. A temporary solution could be an update to the latest version of Spigot. This helped @Guss in referenced issue.

I haven't thought about the possibility yet that you're able to use my "easter egg" as a method to spam. This feature gets removed in v1.9.1 and maybe returns some day.

Kind regards,
KingDome24

**Comment by KingDome24** [comment]
Hello,

this issued should now be fixed. Please test v1.9.1 after its release and report any new problems. :)

Kind regards,
KingDome24
