### ISSUE TITLE
Broadcaster not broadcasting config

### ISSUE THREAD

**Issue by VortexPit** [DominicLuidold/SimpleBroadcast#25]
Ok, so I have started messing with your plugin and when I set up the config, it still broadcasts the default messages. 
I have uploaded the file as a zip with the config inside as github does not support yml files
[config.zip](https://github.com/SimpleBroadcast/SimpleBroadcast/files/76308/config.zip)

**Comment by KingDome24** [comment]
Hello,

the reasons causing your problem are the single quotation marks within your messages.
Please replace them with "%sq%" or replace the single quotes at the beginning and end of each message with double quotation marks (").

Kind regards,
KingDome24
